### ISSUE TITLE
Final Cut won't play back as stabilized with Gyroflow data

### ISSUE THREAD

**Issue by timcorbin** [latenitefilms/GyroflowToolbox#19] opened 2023-04-10 17:27 UTC
Chris, a weird one here. I export the Gyroflow project WITH the processed gyro data and load it into the clip in Final Cut. Gyroflow plays back the clip as perfectly stabilized. Final Cut plays it back as still unstabilized. Everything appears to be done correctly according to the workflow, but either I'm missing something or something's not working (I'm sure it's me). I can render out a new video from Gyroflow and it's perfect, but obviously GFT should make that unnecessary. Any ideas?

M1 Max MacBook Pro 32GB RAM
FCP 10.6.5
Gyroflow 1.5.0
Monterey 12.6.4

**Comment by latenitefilms** [comment] 2023-04-11 21:51
Are the FOV, Smoothness & Lens Correction attributes the same as what you have in Gyroflow?

Currently, when you import a Gyroflow Project we don't populate them - so you'll need to manually match them.

If interested, I'm also experimenting with a new version of Gyroflow Toolbox - still a work-in-progress:

https://testflight.apple.com/join/nPBZO2aZ

**Comment by timcorbin** [comment] 2023-04-13 12:27
Yup, those three parameters all match. I'm now  in the experimental version. I could roll back to the current stable release to check there if you want, but the think the settings were still all the same. For now I'm able to render new videos out from Gyroflow, but not having to do that would be awesome.

**Comment by latenitefilms** [comment] 2023-04-15 08:43
Apologies for the delayed reply - I've been on the road. 

So the TestFlight version isn't working for you either?

There is this bug report on the DaVinci Resolve OpenFX repo:

https://github.com/gyroflow/gyroflow-ofx/issues/31

Both the DaVinci Resolve plugin and Gyroflow Toolbox both use `gyroflow_core` (i.e. the main Gyroflow rendering engine) - so it's possible this bug could exist in both plugins.

I'll be back in front of a computer this week, so I'll try and have a proper deep dive into what might be going wrong.

What kind of footage are you working with? Could you share a file?

You can upload here: https://latenitefilms.digitalpigeon.com

**Comment by scrappyTURTLEcom** [comment] 2023-06-09 03:25
I had the same problem today, where fcp would not apply the stabilization data from the GyroFlow processed data file.

In my case, after 6 hours of trying everything under the sun, I figured out the cause. I use an external ssd for my fcp media. if the external ssd is mounted in a directory (like movie) as a Symbolic Link, GyroFlow Toolbox will not locate the GyroFlow data file, therefore no stabilization in fcp.

When I finally deleted the Symbolic Link to the external ssd, and started using the ssd as a drive (shows up in the Finder on the left hand column, everything started working normal.

My guess is that your issue may also be due to a broken link to the GyroFlow processed data file.

Hope this helps.

**Comment by latenitefilms** [comment] 2023-06-09 03:42
Amazing, thanks for the feedback - this is really interesting! I'll do some digging to see if this is something wrong with `gyroflow_core` or Gyroflow Toolbox.

**Comment by scrappyTURTLEcom** [comment] 2023-06-09 03:50
It most likely has to do with the Toolbox, since I could run the GyroFlow Software using the Symbolic Link for my media with no problems.

**Comment by latenitefilms** [comment] 2023-06-09 04:20
Ok, that should be a simple problem to fix. Will look into it ASAP. Thanks again for reporting! I'll make a seperate issue.

**Comment by latenitefilms** [comment] 2023-07-13 04:34
I'm assuming maybe this issue is related to #22 - Gyroflow Toolbox is not yet compatible with Gyroflow v1.5.1 or later.

This will be addressed in Gyroflow Toolbox v1.1.0.

**Closed by latenitefilms** 2023-07-13 04:34 UTC
Labels: waiting on reply, tech support
